### ISSUE TITLE
RecursiveField Assertion Error

### ISSUE THREAD

**Issue by x0x1235** [glowka/drf-yasg-json-api#2]
I am getting an assertion error while trying to generate schema for a ViewSet which contains a `djangorestframework-recursive` - `RecursiveField` 

```
assert use_references is True, "Can not create schema for RecursiveField when use_references is False"
AssertionError: Can not create schema for RecursiveField when use_references is False
```

**serializers.py**
```
class ResourceSerializer(serializers.ModelSerializer):

    children = serializers.ListField(read_only=True, source='get_children', child=RecursiveField())

    class Meta:
        model = Resource
        fields = ('id', 'children', 'slug')
```

Could you please help me out?

**Comment by glowka** [comment]
OK, so it looks like `drf-yasg` implementation of inspector for `RecursiveField` works only if schema generation works in `use_references`.

### Few words of explenation

`drf-yasg` has inline mode `use_references=False` and reference mode `use_references=True`. In the latter, apart from generating endpoints schema, all views` root serializers are treated as *model definitions* which can be referenced. That's pretty reasonable that `drf-yasg` enforce use of referencing as it seems perfect solution for recursive definition.

Currently, `drf-yasg-json-api` is currently compatible only with inline model as it's allow most straightforward implementation of JSON API and integration with `drf-yasg`. While supporting referencing model seems plausible in the future (but would require a bit more development), it does not really matter, because it looks to me that it could be as well supported in inline mode.
**The much more important question is: what `RecursiveField` actually means in terms of JSON API?**

#### `RecursiveField` in JSON API

So I would say that serializer that you posted translates into data of the following shape:

```json
{
  "data":
    {
       "type": "resources",
       "id": "1",
       "attributes": {
           "slug": "my-resource-1"
      },
     "relationships": {
        "children": {
            "data": [
               {"type": "resources", "id": "2"}, 
               {"type": "resources", "id": "3"}, 
            ]
         } 
     }
}
```
What I mean here is that `RecursiveField` is a relation in terms of JSON API

I could add such support of this field as described but...

### How DRFJA supports it

I think it is not supported by [Django REST framework JSON API](https://github.com/django-json-api/django-rest-framework-json-api) and I guess DRFJA just falls back to treating it as any field and puts it in `attributes` instead of `relationships`. This is clearly is non JSON API and almost certainly non-intended.

Correct me if I am wrong in my JSON API interpretation of `RecursiveField` and DRFJA (lack of) support for it.

How `RecursiveField` works for you with DRFJA?

**Comment by x0x1235** [comment]
You are right, `RecursiveField` in serializer will add the data in `attributes` instead of `relationships` and that is what I needed here. Because my model is an MPTT model and am creating a read-only endpoint and I don't want to make multiple API calls to get the full tree list.

When working with DRF-JA, Is there any optimal and proper way to do this?

**Comment by glowka** [comment]
The proper JSON API method for handling this case is response [`included`](https://jsonapi.org/format/#fetching-includes) field which aims exactly that – saving client-server round trips.

DRF-JA supports that by [`included_serializers`](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#included) attribute of `ModelSerializer`.

However, at this point I have some caveats:
 1. I am not sure if the current implementation of `DRF-JA` allows to handle circular dependency. Declaration can be solved lazy property but I am not sure about the internal code.
2. Assuming `DRF-JA` can handle the circular dependency, I am not sure you could take advantage of MPTT as you probably do now. I don't know this lib but it looks like highly optimized in terms of DB read, so some of that could be lost.
3. If you manage to overcome issues above, I will need to add support for circular `included`. It's rather simple edge-case, but don't expect latest release to work out of the box.

Obviously, let me know once you get to point 3.

**Comment by glowka** [comment]
Strategies related to recursion are now described in README: https://github.com/glowka/drf-yasg-json-api/blob/master/README.md#coexistence-of-json-api-views-with-pure-rest-api-views
